language: node_js
node_js:
  - "11.10.1"
addons:
    code_climate:
        repo_token: $CC_TEST_REPORTER_ID
cache:
  directories:
  - node_modules
before_script:
  - npm install codeclimate-test-reporter istanbul -g
script:
  - npm install
  - npm run coverage
after_script:
  - TOKEN_COVERALLS=$coveralls_repo_token npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info