language: node_js
node_js:
  - "11.10.1"
addons:
    code_climate:
        repo_token: $CC_TEST_REPORTER_ID
cache:
  directories:
  - node_modules
before_script:
  - npm install codeclimate-test-reporter istanbul -g
script:
  - npm install
  - npm run coverage
after_success:
  - TOKEN_COVERALLS=$coveralls_repo_token npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
deploy:
  provider: heroku
  app: r-questioner
  on:
    condition: $TRAVIS_BRANCH == develop
    repo: chikeozulumba/questioner-bootcamp-react
    branch: develop
  api_key:
    secure: $HEROKU_AUTH

deploy:
  provider: heroku
  app: r-questioner
  on:
    condition: $TRAVIS_BRANCH == master
    repo: chikeozulumba/questioner-bootcamp-react
    branch: master
  api_key:
    secure: $HEROKU_AUTH